cubeEventServer.cgi: Communication.cpp CubeEventServer.cpp main.cpp
	g++ -o cubeEventServer.cgi  Communication.cpp CubeEventServer.cpp main.cpp -std=c++11

clean:
	rm -rf *.o
mrproper: clean
	rm -rf cubeEventServer.cgi

