CFLAGS=-W -Wall -ansi -pedantic -std=c++11 -lpthread

all: cubeEventServer.cgi

cubeEventServer.cgi : Communication.o CubeEventServer.o  main.o
		g++ -o cubeEventServer.cgi Communication.o CubeEventServeur.o main.o 

Communication.o: Communication.cpp 
		g++ -o Communication.o -c Communication.cpp $(CFLAGS)

main.o: main.cpp CubeEventServer.h
		g++ -o main.o -c main.cpp $(CFLAGS)

CubeEventServeur.o:	CubeEventServeur.cpp 
		g++ -o CubeEventServeur.o -c CubeEventServeur.cpp  $(CFLAGS)

clean: 
		rm -rf *.o
mrproper: clean
		rm -rf cubeEventServer.cgi

